### ISSUE TITLE
running realtime-newsapi and the example page https://codesandbox.io/s/k5q6nwqkrr returns nothing

### ISSUE THREAD

**Issue by nicolauga** [janlukasschroeder/realtime-newsapi#1]
Hello, i came across https://newsfilter.io/ and later your realtime-newsapi git repo.
I played a bit with your Query APi, it is fantastic. However when trying to run the Real Time Streaming API (i'm not a node.js expert but it looks like it's set up correctly) or using the example url https://codesandbox.io/s/k5q6nwqkrr nothing gets returned. Has something changed on your end so that real time doesn't work anymore? If nothing's changed, i'll keep looking.
Thanks!

**Comment by nicolauga** [comment]
Got it reading another of your answers. Thanks.

**Comment by DmitrievichLevin** [comment]
@nicolauga Hey I was wondering if you could link the answer I'm having a similar problem getting the stream to work.

**Comment by janlukasschroeder** [comment]
@DmitrievichLevin you need an active subscription to access the stream API. You can find our API plans here: https://newsfilter.io/api-plans

Hope this helps.

**Comment by DmitrievichLevin** [comment]
I have an active subscription, I’ve edited the code a little and I’m only receiving a response of {“online”:true, “type”:api} it didn’t work out the box even when I added the query params with my key

**Comment by janlukasschroeder** [comment]
@DmitrievichLevin no problem. if you could send us an email at support@newsfilter.io we'll help you straight away.

**Comment by Robeltaddese** [comment]
Hi, just wondering wether the website is still running? I cant seem to subscribe?
