### ISSUE TITLE
The index.js code is not working?

### ISSUE THREAD

**Issue by jmy48** [janlukasschroeder/realtime-newsapi#3]
```
const api = require('realtime-newsapi')();
api.on('articles', articles => {
  console.log(articles);
});
```

Running it logs nothing, but https://newsfilter.io/ is still being updated. Is there an endpoint for accessing the stream?

**Comment by janlukasschroeder** [comment]
Yes, correct - you need an API key. Happy to get you one. You can send an email to support@newsfilter.io and describe your use case (research project or commercial) so that we can issue a key to you.
